name: python CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: python -m unittest discover -s ./tests
